"""LLM-based test planning: user story in, reviewed test plan out.

Two steps (a small "planner + critic" workflow):
  1. PLAN:   Claude reads one user story + its acceptance criteria and drafts test cases.
  2. REVIEW: a second call checks the draft against the ACs and lists what is missing.
  3. CHECK:  plain Python verifies every AC is covered by at least one case (no AI trust needed).
A human (you) reads the result before anything becomes an automated test.

Usage:
  python -m ai.test_planner US-05
  python -m ai.test_planner US-05 --requirements docs/REQUIREMENTS.md
"""
import argparse
import re
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, Field

from ai.llm import ask_structured

ROOT = Path(__file__).resolve().parent.parent
PROMPTS = Path(__file__).parent / "prompts"
OUT_DIR = ROOT / "docs" / "test-plans"


class TestCase(BaseModel):
    __test__ = False  # tell pytest this is not a test class
    id: str = Field(description="e.g. TC-US05-01")
    title: str
    covers: list[str] = Field(description="AC ids this case verifies, e.g. ['US-05 AC1']")
    technique: Literal["positive", "negative", "boundary", "equivalence", "state-transition", "security", "accessibility", "concurrency"]
    layer: Literal["unit", "api", "ui", "db"]
    priority: Literal["P1", "P2", "P3"]
    preconditions: list[str]
    steps: list[str]
    expected: str


class TestPlan(BaseModel):
    __test__ = False
    story_id: str
    risks: list[str] = Field(description="What could break or harm a user, highest risk first")
    open_questions: list[str] = Field(description="Ambiguities to ask the product owner about")
    test_cases: list[TestCase]


class PlanReview(BaseModel):
    missing_scenarios: list[str]
    weak_cases: list[str] = Field(description="Case ids with vague steps or unverifiable expected results, and why")
    verdict: Literal["ready", "needs-work"]


def extract_story(requirements: str, story_id: str) -> str:
    """Return the markdown section for one story, e.g. '## US-05 ...' up to the next '## '."""
    match = re.search(rf"^## {re.escape(story_id)}\b.*?(?=^## |\Z)", requirements, flags=re.M | re.S)
    if not match:
        raise SystemExit(f"Story {story_id} not found")
    return match.group(0).strip()


def acceptance_criteria_ids(story: str, story_id: str) -> list[str]:
    return [f"{story_id} {ac}" for ac in re.findall(r"\b(AC\d+)\b", story)]


def uncovered_acs(plan: TestPlan, ac_ids: list[str]) -> list[str]:
    """Deterministic coverage check: the part we do NOT leave to the model."""
    covered = {c.strip() for case in plan.test_cases for c in case.covers}
    return [ac for ac in dict.fromkeys(ac_ids) if ac not in covered]


def to_markdown(plan: TestPlan, review: PlanReview, missing: list[str]) -> str:
    lines = [f"# Test plan: {plan.story_id}", "", "> Draft generated by ai/test_planner.py. Reviewed by: _(your name)_", ""]
    lines += ["## Risks", *[f"- {r}" for r in plan.risks], ""]
    lines += ["## Open questions", *[f"- {q}" for q in plan.open_questions], ""]
    lines += ["## Test cases", "", "| ID | Title | Covers | Technique | Layer | Priority |", "|---|---|---|---|---|---|"]
    lines += [f"| {c.id} | {c.title} | {', '.join(c.covers)} | {c.technique} | {c.layer} | {c.priority} |" for c in plan.test_cases]
    for c in plan.test_cases:
        lines += ["", f"### {c.id}: {c.title}", "**Preconditions:** " + "; ".join(c.preconditions),
                  "", *[f"{i}. {s}" for i, s in enumerate(c.steps, 1)], "", f"**Expected:** {c.expected}"]
    lines += ["", "## AI review", f"Verdict: **{review.verdict}**", "", "Missing scenarios:",
              *[f"- {m}" for m in review.missing_scenarios], "", "Weak cases:", *[f"- {w}" for w in review.weak_cases]]
    lines += ["", "## Coverage check (deterministic)",
              "All acceptance criteria covered." if not missing else "NOT covered: " + ", ".join(missing)]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("story_id")
    parser.add_argument("--requirements", default=str(ROOT / "docs" / "REQUIREMENTS.md"))
    args = parser.parse_args()

    story = extract_story(Path(args.requirements).read_text(encoding="utf-8"), args.story_id)
    print(f"Planning {args.story_id}...")
    plan = ask_structured((PROMPTS / "planner_system.md").read_text(encoding="utf-8"), story, TestPlan)

    print("Reviewing the draft...")
    review = ask_structured(
        (PROMPTS / "reviewer_system.md").read_text(encoding="utf-8"),
        f"<story>\n{story}\n</story>\n\n<draft_plan>\n{plan.model_dump_json(indent=2)}\n</draft_plan>",
        PlanReview,
    )
    missing = uncovered_acs(plan, acceptance_criteria_ids(story, args.story_id))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / f"{args.story_id}.md"
    out.write_text(to_markdown(plan, review, missing), encoding="utf-8")
    print(f"Wrote {out.relative_to(ROOT)}  |  {len(plan.test_cases)} cases  |  review: {review.verdict}"
          + (f"  |  UNCOVERED: {missing}" if missing else ""))


if __name__ == "__main__":
    main()
